spring.application.name=api-boleto

# H2 CONFIG
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:boleto
spring.datasource.username=sa
spring.datasource.password

# SQL CONFIG
spring.jpa.hibernate.ddl-auto=update

# KAFKA CONFIG
spring.kafka.bootstrapServers=localhost:19092
spring.kafka.topico-boleto=solicitacao-boleto
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
