spring.application.name=validador-boleto

# PROJECT CONFIG
server.port=8383

# H2 CONFIG
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:boleto
spring.datasource.username=sa
spring.datasource.password

# SQL CONFIG
spring.jpa.hibernate.ddl-auto=update

# KAFKA
spring.kafka.bootstrap-servers=localhost:19092
spring.kafka.consumer.group-id=validador-boleto
spring.kafka.topico-boleto=solicitacao-boleto
spring.kafka.producer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

# AVRO
spring.kafka.properties.schema.registry.url=http://localhost:8081
spring.kafka.properties.specific.avro.reader=true